### ISSUE TITLE
Incr / diff backup

### ISSUE THREAD

**Issue by ryszard-suchocki** [n-mam/offset#2]
Hello,
I have a few questions:
What kind of backup is performed during the process? Block-based or file-based?
Is it possible to take an incr or diff backup type? 

BR

**Comment by n-mam** [comment]
Hi

The backup/conversion is done at volume block level using the either vhd or vhdx as the container format. Incremental volume level backup would need some kind of change tracing mechanism (ideally in kernel) to maintain the list of changed blocks at various points in time.  I plan to do that in future releases. For hyper-v, I do have code in the repo which can create  an incremental backup using hyper-v RCT CBT (check file rtc) That was functional when I last checked, though I have not surfaced that on the UI in any form. That is also in pipeline.

**Comment by ryszard-suchocki** [comment]
Please look at [libvshadow](https://github.com/libyal/libvshadow/blob/main/documentation/Volume%20Shadow%20Snapshot%20(VSS)%20format.asciidoc).
