### ISSUE TITLE
Milestones & feature

### ISSUE THREAD

**Issue by ryszard-suchocki** [n-mam/offset#5]
Hello,
I see that some cam/recorder-related features are being implemented. Can you shed some light on the new part or any other plans for the future?

BR!

**Comment by n-mam** [comment]
yes indeed. i am working on a IP/rtsp camera dashboard which would have face detection and recognition capability using opencv.. hopefully the initial implementation should be out in the next 3 weeks.

**Comment by ryszard-suchocki** [comment]
OK :) How it is related to software that takes block image of volume?

**Comment by n-mam** [comment]
Yes I know.. it is not related to image backups.. Ill move this outside in its own repo. same with FTP tab as well.
